# Generated by Django 4.0.1 on 2022-01-19 15:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('1', 'Active'), ('0', 'Inactive')], max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('date', models.DateField(auto_now_add=True)),
                ('status_transaction', models.CharField(choices=[('0', 'closed'), ('1', 'reversed'), ('2', 'pending')], max_length=1)),
                ('status_approved', models.BooleanField()),
                ('final_charge_done', models.BooleanField(default=False)),
                ('company_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='APIapp.company')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
