# Generated by Django 4.0.1 on 2022-01-25 02:33

import APIapp.utils
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.CharField(default=APIapp.utils.generate_random_company_id, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('ACTIVE', 'active'), ('INACTIVE', 'inactive')], default='ACTIVE', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date', models.DateTimeField()),
                ('status_transaction', models.CharField(choices=[('CLOSED', 'closed'), ('REVERSED', 'reversed'), ('PENDING', 'pending')], default='PENDING', max_length=20)),
                ('status_approved', models.BooleanField()),
                ('final_charge_done', models.BooleanField(default=True)),
                ('company_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='APIapp.company')),
            ],
            options={
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date'],
            },
        ),
    ]
