# Generated by Django 4.0.1 on 2022-01-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Transactions'},
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='final_charge_done',
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('0', 'Inactive')], default='Active', max_length=1),
        ),
    ]
