# Generated by Django 4.0.1 on 2022-01-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIapp', '0002_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('0', 'Inactive')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status_transaction',
            field=models.CharField(choices=[('0', 'closed'), ('1', 'reversed'), ('2', 'pending')], max_length=20),
        ),
    ]
