# Generated by Django 4.0.1 on 2022-01-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIapp', '0003_alter_company_status_alter_transaction_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
