# Generated by Django 4.0.1 on 2022-01-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIapp', '0005_alter_company_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'active'), ('INACTIVE', 'inactive')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status_transaction',
            field=models.CharField(choices=[('CLOSE', 'closed'), ('REVERSED', 'reversed'), ('PENDING', 'pending')], max_length=20),
        ),
    ]
