# Generated by Django 4.0.1 on 2022-01-21 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIapp', '0007_transaction_final_charge_done'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name_plural': 'Companies'},
        ),
    ]
