# Generated by Django 4.0.1 on 2022-01-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIapp', '0008_alter_company_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status_transaction',
            field=models.CharField(choices=[('CLOSED', 'closed'), ('REVERSED', 'reversed'), ('PENDING', 'pending')], default='PENDING', max_length=20),
        ),
    ]
