# Generated by Django 4.0.1 on 2022-01-22 13:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('APIapp', '0010_alter_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
