# Generated by Django 4.0.1 on 2022-01-22 13:43

import APIapp.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIapp', '0011_alter_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.CharField(default=APIapp.utils.generate_random_company_id, editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
